---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:314146295673:task-definition/python-task-def:1"
        LoadBalancerInfo:
          ContainerName: "python-cont"
          ContainerPort: 5000
